---
title: "Isolator drift universal kriging"
author: "Huy Pham"
date: "8/20/2021"
output: html_document
---

---

# Data loading

```{r setup, include=FALSE, echo = T, results = 'hide'}
library(ggplot2)
library(tidyverse)
library(pscl)
library(ResourceSelection)
library(caret)
library(DiceKriging)

rm(list = ls())

point.col = rgb(red=0.3, green=0.3, blue=0.3, alpha=0.4)  # point color for the plots
par(mfrow = c(2,2))
```

Limit ground motions to only those with scale factor less than 20.

```{r}
# current data set also includes manual bandpass and Mag&Rjb
dataPath <- '../pastRuns/isolData.csv'
isol.full <- read.csv(dataPath, header=TRUE) %>% 
  filter(GMScale <= 20)
```



Organize outputs. Currently, we record maximum interstory drift and any collapse between the three levels.
```{r}
isol.full$maxDrift <- pmax(isol.full$driftMax1, isol.full$driftMax2, isol.full$driftMax3)
isol.full$collapse <- ((isol.full$collapseDrift1 | isol.full$collapseDrift2) |
  isol.full$collapseDrift3) %>%
  as.integer()

isol.full$collapseFac <- ((isol.full$collapseDrift1 | isol.full$collapseDrift2) |
  isol.full$collapseDrift3) %>%
  as.factor()

isol.full$impactFac <- isol.full$impacted %>% as.logical %>% as.factor()

# isol.full <- filter(isol.full, impacted == 0)

```

Optionally, gather the dimensionless variables

```{r}
zetaRef     <- c(0.02, 0.05, 0.10, 0.20, 0.30, 0.40, 0.50)
BmRef       <- c(0.8, 1.0, 1.2, 1.5, 1.7, 1.9, 2.0)
tmp <- unlist(approx(zetaRef, BmRef, isol.full$zetaM)[2])
isol.full$Bm  <- tmp

g <- 386.4

# nondims
isol.full$TfbRatio <- isol.full$Tfb/isol.full$Tm
isol.full$mu2Ratio <- isol.full$mu2/(isol.full$GMSTm / isol.full$Bm)
isol.full$gapRatio <- isol.full$moatGap*4*pi^2/((isol.full$GMSTm/isol.full$Bm) *
                                       g * isol.full$Tm^2)
isol.full$T2Ratio <- isol.full$T2/isol.full$Tm
isol.full$Qm <- isol.full$mu2*g
```


# Universal kriging

```{r}
X <- data.frame(isol.full$gapRatio, isol.full$RI)
y <- isol.full$maxDrift

mlog <- km(design = X, response = y, covtype = 'gauss')
plot(mlog)
```

